spring:
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    tomcat:
      max-wait: 3000
      max-active: 10
      max-idle: 10
      min-idle: 10
      initial-size: 10
    url: "jdbc:mariadb://localhost:3306/kakaopay?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul"
    username: "root"
    password: "123456"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
---